# Generated by Django 3.2.5 on 2021-07-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='actor_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='actor representation'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
