# Generated by Django 3.2.6 on 2021-08-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_logentry_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
    ]
